[#133] Task02 / create custom bottom sheet function
bbangmap/BBangMap-iOS pull request #140
Opened 2021-12-11 08:02 UTC by havetherain

- Custom Bottom Sheet 동작 정의

## 종류
- [x] New Feature
- [ ] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요

## 변경 사항

## 참고 사항

2021-12-12 08:00 UTC, 5anniversary requested changes

2021-12-12 08:02 UTC, havetherain commented on BBangmap/BBangmap/Global/DesignSystem/View/BottomSheetView.swift
>          .disposed(by: disposeBag)
withUnretained 사용법에 익숙치않아서 그냥 지운것 같습니당...
좀 더 확인해볼게요!

2021-12-13 01:47 UTC, 5anniversary approved these changes
view라는 네임은 이미 가지고 있는데가 많아서... 
나중에는 그냥 owner로 바꿔주세요~~

2021-12-13 01:47 UTC, 5anniversary commented
LGTM 👍

2021-12-14 07:32 UTC, ezidayzi approved these changes

2021-12-14 07:59 UTC, ehdustj1001 approved these changes

2021-12-17 16:11 UTC, 5anniversary commented
요건 언제 머지해주시나요?! 확인해주세요~

2021-12-17 21:53 UTC, merged