[#42] Task03 / refactor search review layout
bbangmap/BBangMap-iOS pull request #146
Opened 2021-12-14 19:05 UTC by ezidayzi

## 종류
- [ ] New Feature
- [ ] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
searchVC 버릭리고 ... 다시 맹글었어요
![simulator_screenshot_154AC26B-8CE8-4EB5-AB6D-584E9E27CEC2](https://user-images.githubusercontent.com/72497599/146062892-080f4e2a-2362-479b-b0b6-56b50c4847d5.png)

# 질문사항
```swift
extension Reactive where Base: SearchReviewOptionView {
    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
        let online = base.onlineButton.rx.tap
            .map { _ -> Bool in
                return base.onlineButton.isSelected
            }

        let vegan = base.veganButton.rx.tap
            .map { _ -> Bool in
                return base.veganButton.isSelected
            }

        return Observable.combineLatest(online, vegan)
            .asDriver(onErrorJustReturn: (false, false))
    }
}
```
이렇게 해서 탭할때마다 각각의 버튼의 상태를 받아오도록 했는데,
문제는! 처음 뷰에 그려졌을 때 작동을 잘 하지 않는다는 겁니다요..
버튼 둘다 선택된 이벤트가 있어야만 작동하더라구요.. 
어떻게 하면 이벤트 발생 없이 초기 상태의 (false,false) 값을 가져올 수 있을 까요?

2021-12-15 07:07 UTC, jeongyeob97 commented
Observable.combineLatest(online, vegan)이거 대신 Observable.merge를 하면 괜찮을 거 같아요

2021-12-15 09:02 UTC, ezidayzi commented
> Observable.combineLatest(online, vegan)이거 대신 Observable.merge를 하면 괜찮을 거 같아요

근데 두가지 값 모두 방출해야해서..ㅠ 머지하면 하나만 방출되지 않나요..?

2021-12-17 16:11 UTC, 5anniversary requested changes

2021-12-17 16:11 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
요거를 Driver로 선택해준 이유가 뭘까요?!

2021-12-17 16:11 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewTextFieldView.swift
> +        )
오우야...

2021-12-17 16:11 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewTextFieldView.swift
> +            })
`withUnretained`의 사용법에 맞지 않습니다! 좀더 알아봐주세요!

2021-12-17 16:11 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewTextFieldView.swift
> +            .disposed(by: disposeBag)
여기도~

2021-12-17 16:11 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewViewController.swift
> +            .disposed(by: disposeBag)
여기서는 약한참조 안해주시나요~?!

2021-12-17 16:11 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewViewController.swift
>                  return self.listType
여기도 약한참조 ㅎ...

2021-12-17 16:11 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewViewController.swift
> +            .disposed(by: disposeBag)
약한 참조.... ㅎ

2021-12-17 16:11 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/ViewModel/SearchReviewViewModel.swift
> +            .debounce(.milliseconds(300), scheduler: MainScheduler.instance)
요 이유는 무엇인가요?!

2021-12-18 07:32 UTC, havetherain commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewTextFieldView.swift
> +        )
아래 블로그 글처럼 바꾸는게 더 좋지 않을까 싶은 생각이 드네요 ㅎ..
https://cozzin.tistory.com/27

2021-12-18 07:35 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewTextFieldView.swift
> +        )
ㅎ..ㅎ좋아요

2021-12-18 07:35 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewTextFieldView.swift
> +            })
네에

2021-12-18 07:36 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/SearchReview/ViewModel/SearchReviewViewModel.swift
> +            .debounce(.milliseconds(300), scheduler: MainScheduler.instance)
계속 입력할때마다 서버로 호출이 가는데 디바운싱을 줘야 서버에 부담이될것같아서요~

2021-12-18 07:38 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
사실 이유는 없고..... 방출이 잘 안되어서 바꿔보았습니다

2021-12-18 08:07 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/ViewModel/SearchReviewViewModel.swift
> +            .debounce(.milliseconds(300), scheduler: MainScheduler.instance)
🆗

2021-12-18 08:08 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
흐음?!

2021-12-18 08:08 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
이해가 안됩니다

2021-12-18 08:08 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
PR 설명 맨밑에룰 봐주세요!!

2021-12-18 08:10 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
combineLatest라서 그렇습니다... 정엽이 말처럼 merge로 바꿔주세요 🙏

2021-12-18 08:12 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
흠...아니네... 잠시만요...

2021-12-18 08:12 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
Observable<(Bool, Bool)> 로 반환해야해요 ㅠ

2021-12-18 08:13 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
그렇게되면... BehaviorSubject를 한번 알아보시겠습니까?! 확인해주세요
🙏

2021-12-18 08:13 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
skip으로 첫번째값만 무시하면 되시겠습니다

2021-12-18 08:27 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
해결 완~~

2021-12-18 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
어떻게 해결하셨나요~

2021-12-18 08:28 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
```swift
var didTappedSearchFilterButtons: BehaviorSubject<(Bool, Bool)> {
        let result = BehaviorSubject<(Bool, Bool)>(value: (false, false))

        Observable.merge(
            base.onlineButton.rx.tap.map {_ in},
            base.veganButton.rx.tap.map {_ in}
        )
            .bind(onNext: { _ in
                result.onNext((base.onlineButton.isSelected, base.veganButton.isSelected))
            })
            .disposed(by: base.disposeBag)

        return result
    }
```

2021-12-18 08:30 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/SearchReview/View/SearchReviewOptionView.swift
> +    var didTappedSearchFilterButtons: Driver<(Bool, Bool)> {
오호...
요것도 좋은데 Cell 안에 BehaviorSubject를 두개 만들고 그걸 combineLastest로 연결하는것도 좋을거같아요!

cell 안에서 두 버튼 누르는걸 bind 시켜주시구요

2021-12-20 14:57 UTC, ezidayzi commented
머지 갈겨도 대나요

2021-12-20 14:59 UTC, merged

2021-12-20 15:05 UTC, 5anniversary commented
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 뭐야 왜 물어봤어

2021-12-20 15:16 UTC, ezidayzi commented
> ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 뭐야 왜 물어봤어

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ다 잘거같아서 걍 했는데 안잤네 ? ㅎ-ㅎ?

2021-12-20 15:16 UTC, 5anniversary commented
회사에여~