[#12] CollectionView Layout 세팅 작업
bbangmap/BBangMap-iOS pull request #25
Opened 2021-11-09 06:04 UTC by ezidayzi

## 종류
- [ ] New Feature
- [ ] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
Collection View Layout 세가지를 Custom Layout으로 작성하였습니다

대신 `layoutType` 을 꼭 지정해줘야합니다

## 변경 사항
```swift
enum BBangCollectionViewType {
    case recommendation
    case recent
    case photo
}
```

세가지 종류가 있으며 BBangCollectionViewLayout 생성을 통해 VC에서 따로 레이아웃을 잡아주지 않아도 레이아웃이 잡힙니다
(item 사이 간격이나 contentInset을 따로 지정하지 않아도 됩니다)

## 참고 사항
**BBang Collection View Layout 부분만 리뷰 부탁드립니다~!!
(다른부분은 작업중!)**

## recommendation
![Simulator Screen Shot - iPhone 12 Pro - 2021-11-09 at 14 51 50](https://user-images.githubusercontent.com/72497599/140870133-cd231570-226f-4ed6-8727-af85664ba0a4.png)

## photo
![Simulator Screen Shot - iPhone 12 Pro - 2021-11-09 at 14 52 08](https://user-images.githubusercontent.com/72497599/140870138-cee8a777-18ea-40fa-b1e0-5b2b871727cd.png)

## recent
![Simulator Screen Shot - iPhone 12 Pro - 2021-11-09 at 14 52 22](https://user-images.githubusercontent.com/72497599/140870140-339e5766-bdb1-43c3-a4e3-3296b18f7991.png)

2021-11-09 06:05 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +final class ReviewListViewController: BaseViewController {
여기는 작업중!!!

2021-11-09 07:32 UTC, 5anniversary requested changes
커스텀 콜렉션 레이아웃을 잡으려고 하신 이유가 궁금하네요...

좋은생각인것 같습니다 :페페_굿:

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +            }
제가 else문을 별로 안좋아 하는데 그걸 해소할수있는 방법이 있습니다.

enum에 variable 데이터를 넣어주면 되는데요 

~~~swift
enum BBangCollectionViewType {
     case recommendation
     case recent
     case photo
 }

extension BBangCollectionViewType {
    var itemSize: CGSize {
        switch self {
             case .recommendation:
                 if indexPath.item % 3 == 0 {
                     returnCGSize(width: contentWidth, height: contentWidth / 2)
                 } 
                 return CGSize(width: contentWidth / 2, height: contentWidth / 2)

             case .recent:
                 return CGSize(width: contentWidth, height: contentWidth / 2)

             case .photo:
                 return  CGSize(width: contentWidth / 2, height: contentWidth / 2)
        }
    }
}
~~~


~~~swift

let itemSize = layoutType.itemSize 

~~~

로 잡아주면 매우매우 깔끔해집니다

왜 이렇게 하냐 생각을 하신다면 enum 값에 종속되는 값은 이렇게 바꾸어주면 enum 값에 따라서 변동이 있는 값들을 한눈에 볼수있어서 매우매우 좋습니다.

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +class BBangCollectionViewLayout: UICollectionViewLayout {
왜 CollectionViewLayout인지 물어봐도 될까요?! 
UICollectionViewFlowLayout으로 하는게 설정하는데 공수가 더 안 들어갈거같습니다!

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +    func setLayouts() {
만약에 이 파일 안에서만 불려지는 메소드라면 private 으로 바깥에서 불러올수없게 해주세요 🙏

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +            let attributes = UICollectionViewLayoutAttributes.init(forCellWith: indexPath)
`UICollectionViewLayoutAttributes(forCellWith: indexPath)`로 헤주실수있나요?!

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +                                                   right: collectionViewInset - itemSpacing/2)
저는 여기서 코드를 짠다면 
~~~swift
let halfOfSpacing = itemSpacing / 2
collectionView.contentInset = UIEdgeInsets(
    top: -halfOfSpacing,
    left: collectionViewInset - halfOfSpacing, 
    bottom: halfOfSpacing, 
    right: collectionViewInset - halfOfSpacing
)
~~~

로 해줄 것 같습니다!

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +                                                   right: collectionViewInset - itemSpacing/2)
딱히 이유는 없고 이름으로 값을 알수있는게 저는 좋은거 같아요.
그리고 저는 한줄로 선언을 못 해준다면 린트를 저렇게 잡아주는걸 선호합니다!

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +    }
여기 이 메소드가 필요한 이유는 무엇인가요?!

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +    private var collectionView: UICollectionView!
variable로 선언해주는것은 피해주세요!

최대한 let 혹은 lazy var로 해주세요 그리고 코드 사이사이에 강제로 지정해주시면 보기에도 안좋습니다... 🙏 

~~~swift 
   private let collectionView: UICollectionView = {
       let layout = BBangCollectionViewLayout()
       let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
       ~ 콜렉션뷰 세팅값들 ~
      return collectionView
   }()
~~~

을 선호합니다 메소드로 해주는것보다 한번에 세팅하는게 보기에도 좋고 콜렉션뷰 세팅값을 다른 메소드에서 찾을일이 없어서 좋습니다.

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +        collectionView = UICollectionView(frame: frame, collectionViewLayout: layout)
프레임 베이스로 레이아웃을 잡는게 아니기 때문에 view.frame을 가져오실 필요는 없습니다 🙏

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +        let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as UICollectionViewCell
let cell: 셀 인스턴스 = collectionView.dequeueReusableCell(forIndexPath: indexPath)
로... 해주시면 감사하겠습니다 🙏 

취향이긴 한데... 보기에는 위에 방식이 좋더라구요

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +        }
한번 쓰고 말거기 때문에 약한참조는 필요없습니다! 🙏

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +
아래에서 작성을 하다보니 init시점에 BBangCollectionViewType을 지정해서 주는게 좋을거같은데 어떻게 생각하시나요??!

~~~swift
private let layoutType: BBangCollectionViewType
init(type: BBangCollectionViewType) {
   super.init()
   layoutType = type
}
~~~

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap.xcodeproj/project.pbxproj
> +				DDC1DAFA2739BC3F00C36388 /* BBangCollectionViewLayout.swift */,
요 파일에 알맞는 폴더를 생성해서 넣어주세요... 🙏 

혼자 바깥에 있으니 외로워보이네요... 😭

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +
요 이름이 정해진 기준은 무엇인가요?!

디자인 시스템에 정의되어있는지 궁금하네요 🤔

2021-11-09 07:32 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +
추후에 레이아웃 타입이 변동되지 않을것이라면 이게 좋을듯 합니다... :호호:

2021-11-09 07:33 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +class BBangCollectionViewLayout: UICollectionViewLayout {
그리고 상속을 해서 사용하지 않을거 같은데 final로 선언하지 않은 이유가 있을까요?!

2021-11-09 07:33 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +            }
오호호 ... 감사합니다 !!!

2021-11-09 07:33 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +    func setLayouts() {
넵!

2021-11-09 07:33 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +            let attributes = UICollectionViewLayoutAttributes.init(forCellWith: indexPath)
수정할게요~!~!

2021-11-09 07:34 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +                                                   right: collectionViewInset - itemSpacing/2)
좋은것같습니당~!!

2021-11-09 07:34 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +    }
최신순/추천순에 따라서 레이아웃이 바껴야해요!

2021-11-09 07:35 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +    private var collectionView: UICollectionView!
오호호 넵!!

2021-11-09 07:35 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +    }
😮 ...
아하하ㅏㅏㅏ... 그런거였군요...

2021-11-09 07:35 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +        let cell = collectionView.dequeueReusableCell(forIndexPath: indexPath) as UICollectionViewCell
그런것같네요 수정하겠쑵니당!!

2021-11-09 07:36 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +        }
오호,, 클로져에서는 항상 해주어야하는 줄 알았는데 그건 또 아닌가보네여.. 공부해볼게요!! 감사합니당

2021-11-09 07:36 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +    private var collectionView: UICollectionView!
최신/추천 나뉜다는것을 들으니..........
lazy var로 선언해서 바깥에 BBangCollectionViewLayout을 두는게 좋을거 같아요 다시한번 확인해주세요 🙏

@ezidayzi

2021-11-09 07:36 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +
필터에 따라서 레이아웃을 변경해주어야해서 init 시점에 넣어주기가 애매하드라구요...?? 어떻게 생각하시나요

2021-11-09 07:37 UTC, ezidayzi commented on BBangmap/BBangmap.xcodeproj/project.pbxproj
> +				DDC1DAFA2739BC3F00C36388 /* BBangCollectionViewLayout.swift */,
폴더를 어디에 넣어줘야할지 몰라서.. ,, 추천해주세요.. DesignSystem은 아닌것 같고...

2021-11-09 07:38 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +
그건 아니고 비슷한 형태의 레이아웃을 사용하는게 세가지 (추천순, 최신순) / 사진리스트 여서 네이밍을 요로코롬 했서용

2021-11-09 07:39 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +class BBangCollectionViewLayout: UICollectionViewLayout {
아 ㅎㅎ 뺴먹었어요 수정하겠습니다! UICollectionViewFlowLayout의 메소드나 값을 사용하고 있지않아서 CollectionViewLayout으로 지정했어요!

2021-11-09 07:39 UTC, 5anniversary commented on BBangmap/BBangmap.xcodeproj/project.pbxproj
> +				DDC1DAFA2739BC3F00C36388 /* BBangCollectionViewLayout.swift */,
함께 생각을 해보도록 합시다... :호호:

어디가 좋을까요...
앞으로 이런게 많아질듯한데...

2021-11-09 07:40 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +
몬가 형태로 나누는게 좋지 않을까?! 라는 생각이 들어요...

2021-11-09 07:40 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +    private var collectionView: UICollectionView!
녭!!

2021-11-09 07:41 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +
저도 그렇게 생각해요!!!  네이밍을 다시 고민해보겠숩니다...

2021-11-09 07:41 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +        }
[medium](https://medium.com/flawless-app-stories/you-dont-always-need-weak-self-a778bec505ef)
여기에도 글을 남겨봅니다 :호호:

2021-11-09 07:43 UTC, ezidayzi commented
> 커스텀 콜렉션 레이아웃을 잡으려고 하신 이유가 궁금하네요...
> 
> 좋은생각인것 같습니다 :페페_굿:

커스텀 레이아웃을 잡은 이유는 비슷한 형태의 컬렉션뷰가 여러곳에서 사용이 되고 있고,, 결정적으로는 필터에 따라 레이아웃을 변경해주어야하기때문에 커스텀레이아웃으로 선택했습니다!! 다른 방법도 많을거 같긴하지만...

2021-11-09 07:57 UTC, 5anniversary reviewed
추가로 코멘트 달아봅니다. 🙏

2021-11-09 07:57 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +
🙏

2021-11-09 07:57 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +        }
여기도 몬가 
~~~swift
guard let collectionView = collectionView else { return .zero }
~~~
가 깔끔해보이는군요... :호호:

2021-11-09 07:57 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +         return visibleLayoutAttributes
뭔가 for 앞에 화이트 스페이스가 한칸 들어간거같은데 확인 해주세요 🙏

2021-11-09 07:57 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +         return visibleLayoutAttributes
아니군요 var 앞에 한칸이 빠진거 였네요

2021-11-09 07:57 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(customView: filterButton)
~~~swift
guard let navigationBar = navigationController?.navigationBar else { return }
navigationBar.prefersLargeTitles = true
navigationBar.largeTitleTextAttributes = [
     NSAttributedString.Key.foregroundColor: Color.bbangBlack,
     NSAttributedString.Key.font: UIFont.systemFont(ofSize: 20, weight: .medium)
]
~~~
가 좋을듯 한데... 하... 이거 네비바 설정을 어떻게 해야할지 머리가 아프네요.
커스텀 해주기에는 사이즈가 너무 제각각에 scroll event가 달려있어야하는데...

2021-11-09 07:57 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +                               height: itemSize.height)
여기도 개행 추가해서 잡아주세요~!
~~~swift

CGRect(
     x: xPoint,
     y: yPoint,
     width: itemSize.width,
     height: itemSize.height
)

2021-11-09 07:58 UTC, 5anniversary commented
수정후에! 스샷 옆에 버튼 눌러주세요!
![스크린샷 2021-11-09 오후 4 58 12](https://user-images.githubusercontent.com/22820675/140884664-5fbea81d-93a5-492c-9f4f-71dc23dd4f28.png)

2021-11-09 07:59 UTC, ezidayzi commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +            }
리뷰 반영해보려고 하니 `indexPath` 값과 `contentWidth` 을 알아야해서 어려울 것 같아요 ㅠ

2021-11-09 08:00 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +            }
contentWidth 값은 가져올수가 있는데...아... indexPath...

2021-11-09 08:00 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +            }
제가 생각이 짧았군요... 🙏

2021-11-09 08:01 UTC, 5anniversary commented on BBangmap/BBangmap/Global/BBangCollectionViewLayout.swift
> +            }
깔끔하게만 수정해주세요 🙏

2021-11-09 08:22 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListCoordinator.swift
> +    }
여기서도 궁금한데 코디네이터에 presenter 값을 이용해서 해주는게 push, present 이외에 다른게 있나요??

없다면 상수 let 으로 넣어줘도 될거같은데...

2021-11-09 08:24 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListCoordinator.swift
> +    }
resenter 값을 이용해서 해주는게 push, present 이외에 다른 => 어떤 의미 인가용?!..

2021-11-09 08:26 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListCoordinator.swift
> +    }
presenter가 해주는 역할이 아직은 pushViewController, present 밖에 없는거 같은데 

variable 데이터로 만드는게 좋은가 🤔 생각이 들었어요

2021-11-09 08:27 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListCoordinator.swift
> +    }
let 으로 해주면 presenter를 받아서 넣어주지는 못하지 않나요...?

2021-11-09 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListCoordinator.swift
> +    }
init 시점에 넣어주면 상관이 없어요!

2021-11-09 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListCoordinator.swift
> +    }
한번 해보신다면 알 수 있을겁니다 😎

2021-11-09 08:59 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListCoordinator.swift
> +    }
protocol 때문에 안되는군요... 직접해보고 왔습니다...

2021-11-09 08:59 UTC, 5anniversary approved these changes

2021-11-09 12:43 UTC, ehdustj1001 approved these changes

2021-11-09 12:43 UTC, ehdustj1001 commented on BBangmap/BBangmap/Screen/Map/Review/ReviewListViewController.swift
> +            guard let `self` = self else {return}
이 코드가 필요한 이유 할 수 있을까유?

2021-11-09 12:44 UTC, jeongyeob97 approved these changes

2021-11-10 02:26 UTC, 5anniversary commented
Task도 챙겨주세요! title 변경했습니다. 🙏

2021-11-10 11:00 UTC, merged