[#14] 후기작성 first question view
bbangmap/BBangMap-iOS pull request #32
Opened 2021-11-10 07:12 UTC by ehdustj1001

## 종류
- [x] New Feature
- [ ] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요

<img width="802" alt="스크린샷 2021-11-10 오후 3 56 07" src="https://user-images.githubusercontent.com/68000720/141066473-1a5bf28a-38f9-45d7-9d3c-0a923e66c0fd.png">
## 변경 사항

## 참고 사항

2021-11-10 08:28 UTC, 5anniversary requested changes

2021-11-10 08:28 UTC, 5anniversary commented on BBangmap/BBangmap.xcodeproj/project.pbxproj
> +		48247A34273B7A860039D1DC /* FirstQuestionView.swift in Sources */ = {isa = PBXBuildFile; fileRef = 48247A33273B7A860039D1DC /* FirstQuestionView.swift */; };
파일 이름이 FirstQuestView는 명확하지 않습니다.

빵집이름-어떤CVCell 이 맞지 않나... 생각이 들어요 🤔

2021-11-10 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/FirstQuestion/FirstQuestionView.swift
> +        self.add(grayRoundBackgroundView)
`self` 키워드 제거해주세요! 🙏

2021-11-10 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/FirstQuestion/TypeOfBreadShopButtonView.swift
> +    }
바깥에서 사용하지 않는다면 private로 변경해주세요! 🙏

2021-11-10 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +    private let firstQuestionView = FirstQuestionView()
이렇게 하나하나 붙이는것보다 UICollectionView로 작성하는게 좋을거같은데 어떻게 생각하시나요?!
아니라면 UIScrollView 위에 UIStackView로 작성하는게 좋을거 같아요!

2021-11-10 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +        $0.setImage(UIImage(named: "icQuitOrange"), for: .normal)
enum Image에 해당 이미지 파일이 없었나요?!

2021-11-10 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/FirstQuestion/TypeOfBreadShopButtonView.swift
> +    }
이 라벨은 왜 private 이 아니고 lazy var인가요?!

2021-11-10 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/FirstQuestion/TypeOfBreadShopButtonView.swift
> +    private let circleImageView = UIImageView(image: UIImage(named: "icCircleOff"))
여기도 Image에 파일이 없었나요?!

2021-11-10 08:28 UTC, 5anniversary commented on BBangmap/BBangmap/Global/Extension/UILabel+.swift
> +import Foundation
Foundation이 있어야하나요?!

2021-11-10 09:00 UTC, jeongyeob97 approved these changes

2021-11-10 12:09 UTC, ehdustj1001 commented on BBangmap/BBangmap/Global/Extension/UILabel+.swift
> +import Foundation
앗 없어도 됩니다ㅎㅎ수정하겠습니다!

2021-11-11 08:29 UTC, ehdustj1001 commented on BBangmap/BBangmap/Screen/Review/Register/View/FirstQuestion/FirstQuestionView.swift
> +        self.add(grayRoundBackgroundView)
넵!수정했습니다~

2021-11-11 08:31 UTC, ehdustj1001 commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +    private let firstQuestionView = FirstQuestionView()
스택뷰 사용하는 방향으로 해보겠습니다~!!

2021-11-11 08:33 UTC, ehdustj1001 commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +        $0.setImage(UIImage(named: "icQuitOrange"), for: .normal)
수정했습니다:)

2021-11-11 08:36 UTC, ehdustj1001 commented on BBangmap/BBangmap/Screen/Review/Register/View/FirstQuestion/TypeOfBreadShopButtonView.swift
> +    }
<img width="575" alt="스크린샷 2021-11-11 오후 5 35 14" src="https://user-images.githubusercontent.com/68000720/141265163-0ddac21a-6812-4b91-9bf7-5090f186e20e.png">

다른 뷰에서 텍스트 값을 변경해주려고 lazy var을 사용했습니다!

2021-11-11 09:07 UTC, 5anniversary approved these changes
LGTM 👍

2021-11-11 09:32 UTC, ehdustj1001 commented
리뷰작성뷰 task01 완료했습니다!

2021-11-11 09:33 UTC, merged