Task 02 / review collecion view cell
bbangmap/BBangMap-iOS pull request #34
Opened 2021-11-10 11:56 UTC by ezidayzi

## 종류
- [ ] New Feature
- [ ] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요

## 변경 사항
review collecion view cell 

## 참고 사항
#26 -> 브랜치 요상해서 다시..
이슈티켓 #12

2021-11-10 12:44 UTC, 5anniversary commented
PR이름 변경해주세요 🙏

2021-11-11 09:29 UTC, ehdustj1001 approved these changes
저도 삼항연산자 자주 이용해야겠어요~코드가 훨씬 깰꼼해지는 것같네요ㅎ^^ㅎ

2021-11-11 12:23 UTC, 5anniversary requested changes
리뷰 확인 해주세요〰️

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Global/Coordinator/AppCoordinator.swift
> +        addChildCoordinator(reviewListCoordinator)
수정해주세요! 🙏

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Global/DesignSystem/Button/RecommandationButton.swift
> +        self.contentEdgeInsets = UIEdgeInsets(top: 0,
셀프 키워드는 지워주세요!

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Global/DesignSystem/Button/RecommandationButton.swift
> +        )
~~~swift
addTarget(
    self,
     action: #selector(buttonDidTapped(_:)),
     for: .touchUpInside
)
~~~
으로 수정해주세요 🙏

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Global/DesignSystem/Button/RecommandationButton.swift
> +                                .systemFont(ofSize: 14, weight: .medium)
저는 삼항연산자가 길어질 경우에
~~~swift
titleLabel?.font = isSelected 
     ? .systemFont(ofSize: 14, weight: .bold)
     : .systemFont(ofSize: 14, weight: .medium)
~~~
처럼 합니다 선택이니깐 참고만 해주세요~

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Global/DesignSystem/Cell/BaseCollectionViewCell.swift
> +        self.clipsToBounds = true
여기도 self 키워드 제거해주세요 🙏

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewCollectionViewCell.swift
> +    }
빈 공백 제거해주세요

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewCollectionViewCell.swift
> +        $0.text = "닭가슴살 샌드위치랑 크로와상 샌드위치 사 먹었는데 둘 다 정말 맛있었어요! 닭가슴살 샌드위치랑 크로와상 샌드위치 사 먹었는데 둘 다 정말 맛있었어요!닭가슴살 샌드위치랑 크로와상 샌드위치 사 먹었는데 둘 다 정..."
다시보니깐 서버에서 날아올 텍스트네요...?!

나중에 lint disable은 제거해주세요 🙏

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewCollectionViewCell.swift
> +        $0.text = "구매한 빵"
json으로 넣어줄 시간이 오면 이 text는 제거해주세요 🙏

2021-11-11 12:23 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ReviewCollectionViewCell.swift
> +        ])
~~~swift
contentView.adds([
    reviewImageView,
     dimView,
     breadLabel,
     reviewContentLabel,
     recommandationButton,
     dateLabel
])
~~~
로 수정해주세요 🙏

2021-11-11 12:24 UTC, 5anniversary commented on BBangmap/BBangmap/Global/Coordinator/AppCoordinator.swift
> +        addChildCoordinator(reviewListCoordinator)
trailing white space!!

2021-11-12 05:51 UTC, ezidayzi commented
@5anniversary Button 부분이랑 Coordinator 부분 먼저 코드리뷰 반영했어요!! 다른 리뷰들은 task/review_ViewModel 브랜치에서 수정해서 작업할게여!!

2021-11-12 05:52 UTC, 5anniversary approved these changes
LGTM 👍

나머지는 말씀하신대로 다음 Task에 올려주세요!

2021-11-12 06:25 UTC, merged