[Draft] [#12] Task 03/ Review View Model
bbangmap/BBangMap-iOS pull request #38
Opened 2021-11-14 06:11 UTC by ezidayzi

2021-11-14 06:22 UTC, 5anniversary requested changes

2021-11-14 06:22 UTC, 5anniversary commented on BBangmap/BBangmap/Global/DesignSystem/Cell/BaseCollectionViewCell.swift
> +}
이게 Rounding이 기본으로 들어가는거 같은데 Base 라는 이름이 적절할까요?!

2021-11-14 06:22 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +        dateLabel.text = "21.11.26"
요 시간은 백엔드에서 받아오는게 아닌가요?!

2021-11-14 06:22 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +        ])
contentView.adds([
          reviewImageView,
          dimView,
          breadLabel,
          reviewContentLabel,
          recommandationButton,
          dateLabel
])

로 잡아주세요~~ 🙏

2021-11-14 06:22 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +        let filterButtonIsSelected: BehaviorSubject<Bool> = BehaviorSubject(value: false)
BehaviorSubject는 상태값이 처음에 정해진 상태인데 처음에 정해진 방출값이 필요한가요?!

PublishSubject도 한번 봐주십셔 🙏

2021-11-14 06:22 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +            .disposed(by: disposeBag)
여기에서 왜 disposeBag을 걸어주신거일까요?!

2021-11-14 06:22 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +    }
뷰모델에서만 사용하는거라면 private!!

2021-11-14 06:22 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +            .disposed(by: disposeBag)
disposeBag은 뷰모델에서 보통 사용하지 않습니다!! 🤔

2021-11-14 06:23 UTC, 5anniversary commented
컨플릭트가 있네요 rebase해주세여~!~! 🙏

2021-11-14 07:33 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +        dateLabel.text = "21.11.26"
api가 수정이 안되어있어욥!! 모델 나오면 수정하겠습니당

2021-11-14 07:41 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +        let filterButtonIsSelected: BehaviorSubject<Bool> = BehaviorSubject(value: false)
처음에 false 값을 방출해야 해요! 눌리지않았을때도 필요해서...! 다시 생각해보니 생명주기랑 바인딩해서 초기 값을 세팅해줄 수도 있겠네요  수정해보겠숩니다

2021-11-14 07:43 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +            .disposed(by: disposeBag)
혹시 이거 관련되어서 아티클이나 검색 키워드 같은게 있을까요?? 제가 찾아본 예시 레포나 블로그 글같은 경우에 disposeBag을 ViewModel 에서  사용하고 있는 경우가 많아서여...

2021-11-14 07:43 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +    }
녭~

2021-11-14 07:45 UTC, ezidayzi commented on BBangmap/BBangmap/Global/DesignSystem/Cell/BaseCollectionViewCell.swift
> +}
흠 빵동 대부분의 cell 이 round가 들어가있어서 base로 지었는데 RoundedCollectionViewCell 이 적절하려나여?!

2021-11-14 07:56 UTC, 5anniversary commented on BBangmap/BBangmap/Global/DesignSystem/Cell/BaseCollectionViewCell.swift
> +}
저는 저 round 함수를 익스텐션에 넣으면 어떨까 생각해봅니다 :호호:

2021-11-14 07:56 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +        dateLabel.text = "21.11.26"
🙏👍

2021-11-14 07:56 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +        let filterButtonIsSelected: BehaviorSubject<Bool> = BehaviorSubject(value: false)
네엥~~ 💪

2021-11-14 07:57 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +            .disposed(by: disposeBag)
흠... 이것에 대해서는 한번 설명을 드릴시간이 있었으면 좋겠는데 언제가 좋을까요?!

2021-11-14 08:03 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +            .disposed(by: disposeBag)
여덟시이후로 가능할것 같숩니다~!

2021-11-14 14:49 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +            .disposed(by: disposeBag)
흠... 제가 늦은것인지... :호호:

2021-11-14 14:54 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +            .disposed(by: disposeBag)
우선 제가 Bind 자체를 반대하는 이유는 disposeBag을 ViewController와 ViewModel 양쪽에 만들어주기 때문이에요,
V : VM 은 서로 1:1로 존재한다고 생각하는게 MVVM인데, disposeBag을 굳이 양쪽에 나눠줘야하나?! 🤔 생각이 많이 드는데요. 
부담을 지울수있다면 최대한 지우는 방향이 좋을거 같습니다.

bind로 해주지 않더라도 묶어줄수있는 방법도 많구요, 잘 생각해봐서 메소드 Output을 Observable이나 Publisher로 변환해주면 bind를 쳐주지 않고도 원하는 값으로 만들어줄수도 있습니다. 

이 글을 읽고도 이해가 안된다면 찾아주세여~ 🙌

2021-11-16 05:29 UTC, ehdustj1001 approved these changes
LGTM :)

2021-11-16 05:50 UTC, jeongyeob97 commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +    public let disposBag = DisposeBag()
cell에서 disposeBag 안 쓰는 거 같은데 필요하나요?

2021-11-16 05:50 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +    public let disposBag = DisposeBag()
VC에서 바인딩후 dispose 해줍니다!

2021-11-16 05:51 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/View/ReviewListViewController.swift
> +            .disposed(by: cell.disposBag)
@jeongyeob97 요기!

2021-11-16 05:53 UTC, jeongyeob97 commented on BBangmap/BBangmap/Screen/Map/Review/View/ReviewListViewController.swift
> +            .disposed(by: cell.disposBag)
VC에 있는 disposeBag에 dispose하면 되지 않나요?

2021-11-16 05:54 UTC, jeongyeob97 commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +    public let disposBag = DisposeBag()
스펠링 틀린 거 같아요

2021-11-16 05:54 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/View/ReviewListViewController.swift
> +            .disposed(by: cell.disposBag)
cell 마다 바인딩 해준거라 cell 의 disposeBag에 해주는게 맞다고 생각합니당

2021-11-16 05:55 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +    public let disposBag = DisposeBag()
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ그로네여 수정하겠숩니다

2021-11-16 05:58 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/View/ReviewListViewController.swift
> +            .disposed(by: cell.disposBag)
https://medium.com/@esung/uitableview%EC%97%90%EC%84%9Crxswift%EB%A5%BC%EC%82%AC%EC%9A%A9%ED%95%A0%EB%95%8C%EC%A3%BC%EC%9D%98%ED%95%A0%EC%A0%90-3626500dfb94
@jeongyeob97 참고!

2021-11-16 05:58 UTC, 5anniversary requested changes

2021-11-16 05:58 UTC, 5anniversary commented on BBangmap/BBangmap/Global/Extension/UIView+.swift
> +    }
여기도 cornerRadius값을 받아서 넣어줄수있는 파라미터가 있으면 좋겠네요...
다음 테스크에서 변경해보도록하죠!!

ex func makeRound(radius: Int = 20) {
     ~~~
}

2021-11-16 05:58 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +    public let disposBag = DisposeBag()
prepareForReuse에서 초기화를 해줘야합니다 🙏 

disposeBag = DiseposeBag()

2021-11-16 05:58 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/View/ReviewListViewController.swift
> +import RxCocoa
혹시..이것... 알파벳순으로...

2021-11-16 05:58 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/View/ReviewListViewController.swift
> +    private let viewModel = ReviewListViewModel()
이런 인스턴스 덩어리들은 LifeCycle 위로 올려주세요 🙏

2021-11-16 05:58 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +    private let disposeBag = DisposeBag()
안사라지나요?!

2021-11-16 05:58 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +    }
다시한번 이해를 도와드려야겠군요...

지금 혹시 시간이 되시는지...

2021-11-16 05:58 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +    }
녭 가눙합니다

2021-11-16 05:59 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/ViewModel/ReviewListViewModel.swift
> +    }
잠시... 농땡이 피우러 다른자리로 가겠습니다.. 잠시...

2021-11-16 05:59 UTC, jeongyeob97 commented on BBangmap/BBangmap/Screen/Map/Review/View/ReviewListViewController.swift
> +            .disposed(by: cell.disposBag)
https://medium.com/@esung/uitableview%EC%97%90%EC%84%9Crxswift%EB%A5%BC%EC%82%AC%EC%9A%A9%ED%95%A0%EB%95%8C%EC%A3%BC%EC%9D%98%ED%95%A0%EC%A0%90-3626500dfb94

Cell EndDisplay 했을 때 셀 disposeBag을 새로 생성해서 날려주는 게 좋다고 하네요

2021-11-16 06:00 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/View/ReviewListViewController.swift
> +            .disposed(by: cell.disposBag)
prepareReuse에서 해주도록하겠습니답~!

2021-11-16 06:02 UTC, havetherain approved these changes

2021-11-16 08:16 UTC, 5anniversary approved these changes
LGTM 👍

2021-11-16 09:01 UTC, havetherain commented on BBangmap/BBangmap/Global/Extension/DateFormatter+.swift
> +        guard let date = iso8601Full.date(from: string) else {return ""}
{return ""} 양옆에 스페이스 한칸씩 넣어줄 수 있나요...ㅎ?

2021-11-16 09:02 UTC, havetherain commented on BBangmap/BBangmap/Global/Extension/DateFormatter+.swift
> +    }()
저는 좋아효 ㅎㅎ..
물론 회사에선 지정하는거 귀찮아서 밑에꺼 씁니다...

TimeZone.autoupdatingCurrent
Locale.autoupdatingCurrent

2021-11-16 09:03 UTC, ezidayzi commented on BBangmap/BBangmap/Global/Extension/DateFormatter+.swift
> +        guard let date = iso8601Full.date(from: string) else {return ""}
완료~~

2021-11-16 09:03 UTC, ezidayzi commented on BBangmap/BBangmap/Global/Extension/DateFormatter+.swift
> +    }()
오호... 이렇게 되면 알아서 해당 국가로... 지정해주는 건가요?

2021-11-16 09:03 UTC, 5anniversary approved these changes

2021-11-16 09:03 UTC, 5anniversary commented on BBangmap/BBangmap/Global/Extension/DateFormatter+.swift
> +    }
메소드로 빼주는것도 좋은 방법이긴 한데 

var로 빼주시는게 self키워드를 활용할수가 있어서 좋습니다 :호호:

~~~swift
var convertingString: String {
       guard let date = iso8601Full.date(from: self) else { return "" }
       return dateOnly.string(from: date)
}
~~~

private 으로 type을 만들어준거는 좋은거 같네요!! 이건 제가 배우겠습니다 👍 👍

2021-11-16 09:03 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +        dateLabel.text = DateFormatter.string(iso: review.reviewCreatedDate)
extension을 String+로 만들어주면 좀 더 편하게 사용할수가 있져

var가 date라면

`review.reviewCreatedDate.date` 로 해주면 되니깐요

2021-11-16 09:03 UTC, havetherain approved these changes

2021-11-16 09:04 UTC, havetherain commented on BBangmap/BBangmap/Global/Extension/DateFormatter+.swift
> +    }()
@ezidayzi 예이... 기기별로 설정된 나라 기준으로 자동변환되는 걸로 알고 있어요~

2021-11-16 09:05 UTC, ezidayzi commented on BBangmap/BBangmap/Screen/Map/Review/View/Cell/ReviewCollectionViewCell.swift
> +        dateLabel.text = DateFormatter.string(iso: review.reviewCreatedDate)
오호라
String으로 수정해보겠습니당

2021-11-16 09:10 UTC, 5anniversary commented
머지머지 고고고고

2021-11-16 09:11 UTC, merged