Task/후기 작성 뷰
bbangmap/BBangMap-iOS pull request #49
Opened 2021-11-18 14:13 UTC by ehdustj1001

## 종류
- [x] New Feature
- [ ] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
후기 작성 뷰 마무리 

## 변경 사항

## 참고 사항

2021-11-18 14:55 UTC, 5anniversary requested changes
lint 잘 지켜주세요 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Network/VO/RegisterReviewInfo.swift
> +    enum CodingKeys: String, CodingKey {
요거 수정!! 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/Cell/NameOfBreadCollectionViewCell.swift
> +    override init(frame: CGRect) {
한칸 띄어주세요! 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/Cell/NameOfBreadCollectionViewCell.swift
> +    private func setLayout() {
한칸 띄어주세요! 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/Cell/NameOfBreadCollectionViewCell.swift
> +        if textField.text != "" {
한칸씩 띄어주세요! 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/Cell/NameOfBreadCollectionViewCell.swift
> +        }
저번에 삼향연산자 써보고 싶다고 하셔서...
살짝 줄이는걸 좋아하는듯 하여...
 여기서 쓴다면

`deleteCellButton.isHidden = textField.text == ""`

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/Cell/UploadImageCollectionViewCell.swift
> +    }
한칸씩 띄어주세요! 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/NameOfBoughtBread/NameOfBoughtBreadView.swift
> +    }
생명주기 함수는 각종 컴포넌트, 변수 상수 아래에 넣어주세요!! 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/NameOfBoughtBread/NameOfBoughtBreadView.swift
> +        $0.titleEdgeInsets = UIEdgeInsets.init(top: 6, left: 3, bottom: 7, right: 0)
.init은 빼주시고

`UIEdgeInsets(top~~~)`
이렇게 작성해주세요!!

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RatingOfBread/RatingOfBreadView.swift
> +        questionLabel.snp.makeConstraints {
수정해주세요! 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RatingOfBread/RatingOfBreadView.swift
> +class RatingOfBreadView: UIView {
이것 상속해서 사용하지 않는다면 final 키워드 붙여주세요

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/NameOfBoughtBread/NameOfBoughtBreadView.swift
> +class NameOfBoughtBreadView: UIView {
이것 상속해서 사용하지 않는다면 final 키워드 붙여주세요

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/Cell/UploadImageCollectionViewCell.swift
> +class UploadImageCollectionViewCell: UICollectionViewCell {
이것 상속해서 사용하지 않는다면 final 키워드 붙여주세요

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +        } else if $0.state == .normal {
else 는 빼도 될거같아요!

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +    func collectionView(
수정해주세요!! 🙏 
저는 보통 상속받는것 마다 extension으로 넣어줍니다~

그리고 거기에 맞는 함수만 넣어주기~

그리고 UICollectionViewDelegeteFlowLayout만 써줘도 될 듯 합니다 🙏

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +        }
else는 필요 없을듯 합니다 🙏 

참고참고
https://ichi.pro/ko/if-elseeobsneun-deo-na-eun-sopeuteuweeo-146767889929047

2021-11-18 14:55 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/UploadImages/UploadImagesView.swift
> +    @objc private func tapAddImageButton(_ sender: UIButton) {
수정해주세요 🙏

2021-11-19 01:10 UTC, 5anniversary commented
@ezidayzi @jeongyeob97 
리뷰리뷰 빠르게 빠르게~~

2021-11-19 02:08 UTC, havetherain commented on BBangmap/BBangmap/Screen/Review/Register/Cell/NameOfBreadCollectionViewCell.swift
> +        $0.layer.cornerRadius = 20
@ezidayzi @jeongyeob97 @5anniversary 
cornerRadius 관련해서 UIView+ Extension 만들어놨으니까 한줄로 활용하시면 편해요~

2021-11-19 02:10 UTC, havetherain commented on BBangmap/BBangmap/Screen/Review/Register/Cell/NameOfBreadCollectionViewCell.swift
> +        findShopTextField.placeholder = "빵\(cellIndex+1)"
이건 개인 취향이긴 한데... cellIndex + 1 요렇게 띄우는건 어떻게 생각하십니까 ..

2021-11-19 02:12 UTC, havetherain commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +            $0.backgroundColor = Color.bbangGray
이거 관련해서도 UIButton+ Extension에 setBackgroundColor(_ color: UIColor, for state: UIControl.State)
만들어둬서 편하게 활용하실수 있을거에요 
$0.setBackgroundColor(Color.bbangGray, for: .disabled)
$0.setBackgroundColor(Color.bbangOrange, for: .normal)

2021-11-19 02:15 UTC, havetherain commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +        if ratingOfBreadView.reviewTextView.text == "후기 글은 다른 유저들이 참고할 수 있도록 최소 20자 이상 등록해주세요." {
문구를 하드코딩으로 넣는것보다 열거형 상수를 활용해서 분기처리하면 어떨까요?

else if로 조건문을 애매하게 끝내는것보다 깔끔할것 같아요

2021-11-19 02:19 UTC, 5anniversary commented
개인 취향도 리뷰에 들어가는 군요... 다시해야겠다...

2021-11-19 02:25 UTC, havetherain commented
> 개인 취향도 리뷰에 들어가는 군요... 다시해야겠다...

ㅋㅋㅋㅋㅋㅋ 저건 린트에 안잡히는것 같아서...... 대부분 띄우지 않나요..?

2021-11-19 02:25 UTC, havetherain commented
> 개인 취향도 리뷰에 들어가는 군요... 다시해야겠다...

2021-11-19 02:26 UTC, 5anniversary commented
왜 클로즈?

2021-11-19 06:26 UTC, 5anniversary reviewed
리뷰 확인하고 다시 리퀘스트 해주세요 🙏

2021-11-19 06:26 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +                = collectionView.dequeueReusableCell(forIndexPath: indexPath)
이런식으로 한칸 내리지는 말아주세요 🙏 

너무 길다 싶으면 typealias로 바꿔주세요 🙏 

~~~swift
ex. 
typealias BreadNameCell = NameOfBreadCollectionViewCell
~~~

2021-11-19 06:26 UTC, 5anniversary commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +                = collectionView.dequeueReusableCell(forIndexPath: indexPath)
다른 셀 함수에서도 참고해주세요!

2021-11-19 06:35 UTC, ehdustj1001 commented on BBangmap/BBangmap/Network/VO/RegisterReviewInfo.swift
> +    enum CodingKeys: String, CodingKey {
어떻게 수정하라는 말씀이실까유??

2021-11-19 06:39 UTC, 5anniversary commented on BBangmap/BBangmap/Network/VO/RegisterReviewInfo.swift
> +    enum CodingKeys: String, CodingKey {
아하... 왜 여기에서는... 린트 워닝이 안보이죠... 린트워닝 수정이란 의미였어요!!

2021-11-19 06:39 UTC, 5anniversary commented on BBangmap/BBangmap/Network/VO/RegisterReviewInfo.swift
> +    enum CodingKeys: String, CodingKey {
![스크린샷 2021-11-19 오후 3 39 47](https://user-images.githubusercontent.com/22820675/142576926-a9b4e13f-2911-4684-8c99-1450f05ba2b3.png)

2021-11-19 06:40 UTC, 5anniversary commented on BBangmap/BBangmap/Network/VO/RegisterReviewInfo.swift
> +    enum CodingKeys: String, CodingKey {
file changes에 들어가면 보입니당 🙏

2021-11-19 06:57 UTC, jeongyeob97 commented on BBangmap/BBangmap/Screen/Review/Register/View/RegisterReviewViewController.swift
> +        if ratingOfBreadView.reviewTextView.text == "후기 글은 다른 유저들이 참고할 수 있도록 최소 20자 이상 등록해주세요." {
저도 그게 더 깔끔할거 같아요

2021-11-19 17:46 UTC, ezidayzi commented on BBangmap/Podfile
> +	pod 'Cosmos', '~> 23.0'
요거는 머선 라이브러리 인가여

2021-11-19 17:47 UTC, ezidayzi commented on BBangmap/BBangmap/Global/Resource/Assets.xcassets/icDeleteBox.imageset/Contents.json
>      }
요거 Image Const 파일에 추가해야할 것 같어요 ㅎㅎ

2021-11-21 05:13 UTC, 5anniversary commented on BBangmap/Podfile
> +	pod 'Cosmos', '~> 23.0'
@ehdustj1001 
코스모스는 별점 컴포넌트에서 사용되는 라이브러리입니당 🙏

2021-11-21 05:19 UTC, 5anniversary approved these changes
수고하셨습니다 🙏

2021-11-21 05:22 UTC, merged